### ISSUE TITLE
I broke hard mode walls

### ISSUE THREAD

**Issue by evanugarte** [drofp/RoadRun#39]
Likely due to #35

the walls look like this:
![image](https://user-images.githubusercontent.com/36345325/94770375-56f0c080-0369-11eb-8cce-e1e0d687efbe.png)

**Comment by evanugarte** [comment]
Nevermind, it was due to the terminal being resized. see below it works fine:
![image](https://user-images.githubusercontent.com/36345325/94832261-8aac0480-03c2-11eb-98bc-acc85166ac16.png)

**Comment by drofp** [comment]
Wait too big or too small causes this issue? Or does it only work with a specific terminal size range?

**Comment by evanugarte** [comment]
It happens if you start the game then resize the window

**Comment by drofp** [comment]
maybe we can try to play around with dynamic resizing
